### ISSUE TITLE
vitest-sonar-reporter should probably output errors etc to the console

### ISSUE THREAD

**Issue by clintonmedbery** [AriPerkkio/vitest-sonar-reporter#156]
When I run this with a test that is failing, it outputs the error to the file but it would also be useful to see in the console. Thoughts?

**Comment by AriPerkkio** [comment]
This is something that should be done by Vitest's built-in reporters, like `'verbose'` or `'default'` ones do. You should use those in addition with Sonar reporter.

```ts
    reporters: ['default', 'vitest-sonar-reporter'],
```

**Comment by clintonmedbery** [comment]
Well well well 🤦 
Thank you. Perhaps I will add an example. Feel free to close this.
<img height="200" src="https://media3.giphy.com/media/3oKIPerW9ZwNcp9Y4g/giphy.gif"/>
