### ISSUE TITLE
sonar-report.xml not generated

### ISSUE THREAD

**Issue by bliu13** [AriPerkkio/vitest-sonar-reporter#44]
For some reason the sonar-report.xml file is not being generated.

relevant parts of package.json
```
{
  "devDependencies": {
    "@vitest/coverage-c8": "^0.27.1",
    "c8": "^7.12.0",
    "sonarqube-scanner": "^3.0.0",
    "vite": "^4.0.4",
    "vitest": "^0.27.1",
    "vitest-sonar-reporter": "^0.3.3"
  }
}
```

vite.config.ts
```
import { configDefaults, defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    exclude: configDefaults.exclude,
    testTimeout: 30000,
    reporters: 'vitest-sonar-reporter',
    outputFile: 'coverage/sonar-report.xml',
    coverage: {
      reporter: ['lcov']
    }
  },
})
```

**Comment by AriPerkkio** [comment]
Could you try to help me reproduce this issue? Seems to work fine here: https://stackblitz.com/edit/vitest-dev-vitest-qbwcon

**Comment by bliu13** [comment]
@AriPerkkio, I was able to reproduce it by making some changes to the `package.json`. It looks like it's specifically related to the command `vitest run --coverage --reporter verbose` that I was using. I updated the command against the latest documentation: `vitest run --passWithNoTests --reporter=verbose`. Interestingly, there is a timeout when c8 is generating the report. The lcov.info is empty, but this may be a separate issue that is unrelated.
```
❯ npm run test
$ vitest run --coverage.enabled --passWithNoTests --reporter=verbose

 RUN  v0.27.2 /home/projects/vitest-dev-vitest-3uhu4b
      Coverage enabled with c8

 ✓ test/basic.test.ts (2)
   ✓ Math.sqrt()
   ✓ JSON
 ✓ test/suite.test.ts (3)
   ✓ suite name (3)
     ✓ foo
     ✓ bar
     ✓ snapshot

 Test Files  2 passed (2)
      Tests  5 passed (5)
   Start at  09:00:48
   Duration  6.07s (transform 159ms, setup 0ms, collect 113ms, tests 21ms)

 % Coverage report from c8
close timed out after 10000ms
```

Here's the link with the modifications: https://stackblitz.com/edit/vitest-dev-vitest-3uhu4b

**Comment by AriPerkkio** [comment]
> It looks like it's specifically related to the command `vitest run --coverage --reporter verbose`

The command `vitest run --reporter verbose` sets `reporter: "verbose"`. CLI options override the values of `vitest.config.ts`.

If you wish to override the configuration values using CLI options, specify both reporters: https://vitest.dev/config/#reporters
`vitest run --reporter verbose --reporter vitest-sonar-reporter`

**Comment by bliu13** [comment]
You're right! Updating the configuration fixed the problem. Thank you for pointing out that the reporter config was being overwritten.
