### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by josefernandezatceiba** [AriPerkkio/vitest-sonar-reporter#8]
I have a Vue3 + TS app, when i set it up according to instructions : add the package via yarn, modify vite.config.ts, when i try to run the tests, i get this error : 

Error [ERR_REQUIRE_ESM]: require() of ES Module ~site/node_modules/vitest-sonar-reporter/dist/index.js from ~site/apps/surf-essentials/web-store/vite.config.ts not supported.
Instead change the require of index.js in ~site/apps/surf-essentials/web-store/vite.config.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (~site/apps/surf-essentials/web-store/vite.config.ts:41:44)
    at Object.require.extensions.<computed> [as .ts] (~site/node_modules/vite/dist/node/chunks/dep-9c153816.js:71416:20)
    at loadConfigFromBundledFile (~site/node_modules/vite/dist/node/chunks/dep-9c153816.js:71424:17)
    at loadConfigFromFile (~site/node_modules/vite/dist/node/chunks/dep-9c153816.js:71343:32)
    at async resolveConfig (~site/node_modules/vite/dist/node/chunks/dep-9c153816.js:70873:28)
    at async createServer (~site/node_modules/vite/dist/node/chunks/dep-9c153816.js:56425:20)
    at async createVitest (file://~site/node_modules/vitest/dist/chunk-vite-node-externalize.458f885a.js:10752:18)
    at async startVitest (file://~site/node_modules/vitest/dist/chunk-vite-node-externalize.458f885a.js:10837:15)
    at async CAC.start (file://~site/node_modules/vitest/dist/cli.js:664:9) {
  code: 'ERR_REQUIRE_ESM'
}

I tried changing the "type": "module" in the package.json, but it breaks the project.

Should i do something additional ?? How can i get this package to work with this project ?

**Comment by AriPerkkio** [comment]
The `Error [ERR_REQUIRE_ESM]: require() of ES Module` error message indicates this reporter is imported with `require('vitest-sonar-reporter')` instead of `import SonarReporter from 'vitest-sonar-reporter'`. Could you share your `vite.config.ts` and the run command you are using to run `vitest`?

Here is a working example where `vitest-sonar-reporter` runs just fine: https://stackblitz.com/edit/vitest-dev-vitest-hip4ge?file=vite.config.ts

**Comment by josefernandezatceiba** [comment]
Here's the vite.config.ts and the command is vitest run --coverage 

![image](https://user-images.githubusercontent.com/56275459/161998544-67d28615-7fd8-46cd-a294-2aafb508b686.png)


/// <reference types="vitest" />
import { resolve } from 'path';

import VueI18n from '@intlify/vite-plugin-vue-i18n';
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'
import Legacy from '@vitejs/plugin-legacy';
import Vue from '@vitejs/plugin-vue';
import CleanUp from 'rollup-plugin-cleanup';
import Visualizer from 'rollup-plugin-visualizer';
import Components from 'unplugin-vue-components/vite';
import { defineConfig } from 'vite';
import Inspect from 'vite-plugin-inspect';
import Pages from 'vite-plugin-pages';
import Layouts from 'vite-plugin-vue-layouts';
import SvgLoader from 'vite-svg-loader';


import SonarReporter from 'vitest-sonar-reporter';


export default defineConfig({
  resolve: {
    alias: {
      '~/': `${resolve(__dirname, 'src')}/`,
    },
  },
  plugins: [
    Vue({
      include: [/\.vue$/],
      template: { transformAssetUrls },
    }),
    Inspect(),
    // https://github.com/hannoeru/vite-plugin-pages
    Pages({
      extensions: ['vue'],
    }),

    // https://github.com/JohnCampionJr/vite-plugin-vue-layouts
    Layouts({
      defaultLayout: 'main-layout',
    }),
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    quasar({
      sassVariables: 'src/styles/quasar-variables.sass'
    }),
    // https://github.com/antfu/unplugin-vue-components
    Components({
      extensions: ['vue'],
      dirs: ['src/components', '../../../node_modules/h2o-web-shared/components'],
      include: [/\.vue$/, /\.vue\?vue/],
      dts: 'src/components.d.ts',
    }),
    // https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n
    VueI18n({
      runtimeOnly: true,
      compositionOnly: true,
      include: [resolve(__dirname, 'locales/**')],
    }),
    SvgLoader({
      svgoConfig: {
        multipass: true,
      },
    }),
    CleanUp({
      extensions: ['js', 'mjs', 'vue'],
      comments: ['some', 'istanbul', /STABLE/, /__PURE__/],
    }),
    Legacy({
      ignoreBrowserslistConfig: false,
    }),
    Visualizer({
      filename: resolve(__dirname, 'dist/REPORT/stats.html'),
      template: 'treemap', // sunburst|treemap|network
      sourcemap: true,
      brotliSize: true,
      gzipSize: true,
    }),
  ],
  base: './',
  server: {
    fs: {
      strict: true,
    },
    force: true,
  },
  build: {
    brotliSize: true,
    sourcemap: 'hidden',
    rollupOptions: {
      output: {
        compact: true,
      },
    },
  },
  optimizeDeps: {
    include: [
      'vue',
      'vue-router',
      '@vueuse/core',
      'ky',
      'ramda',
      'pinia'
    ],
    exclude: [
      'vue-demi',
    ],
  },
  test: {   
    watch: false,
    reporters: new SonarReporter(),
    outputFile: 'sonar-report.xml',
    globals: true,
    environment: 'happy-dom',
    exclude: ['integration/*'],
    coverage: {
      exclude: ['__mocks__', '**/*.spec.*', '**/*.test.*'],
      reporter: ['text', 'lcov']
    },
  },
});

**Comment by AriPerkkio** [comment]
Thanks for providing the info. 

> I tried changing the "type": "module" in the package.json, but it breaks the project.

I see, you are trying to use a pure ESM package in a non-ESM project. You'll need to import all ESM modules using dynamic import. Luckily Vite support async config: https://vitejs.dev/config/#async-config.

This should do the trick:

```diff
- import SonarReporter from 'vitest-sonar-reporter';

- export default defineConfig({
+ export default defineConfig(async function () {
+   const { default: SonarReporter } = await import("vitest-sonar-reporter");
+
+  return {  
  ...
  test: {
    reporters: [new SonarReporter()],
```

Let me know if this helps.

**Comment by josefernandezatceiba** [comment]
Bro, thanks a lot. It worked like a charm,  i'm getting code coverage and number of tests 

![image](https://user-images.githubusercontent.com/56275459/162014972-0f62bbcb-8c1a-40f4-a1f3-620d83655c59.png)

**Comment by AriPerkkio** [comment]
Perfect! I'll add this to a troubleshooting section to README in #9.

**Comment by AriPerkkio** [comment]
> This should do the trick:
> 
> ```diff
> - import SonarReporter from 'vitest-sonar-reporter';
> 
> - export default defineConfig({
> + export default defineConfig(async function () {
> +   const { default: SonarReporter } = await import("vitest-sonar-reporter");
> ```
> 

For anyone else running into `ERR_REQUIRE_ESM` error, solution above is no longer recommended.

Instead of importing the reporter, simply let Vitest handle the importing for you. Define reporter as **string** in your `vitest.config.ts`.

> ## Configuration
> 
> Add new custom reporter and define `outputFile` in your [`vite.config.ts`](https://vitest.dev/config/):
> 
> ```ts
> import { defineConfig } from 'vitest/config';
> 
> export default defineConfig({
>     test: {
>         reporters: 'vitest-sonar-reporter',
>         outputFile: 'sonar-report.xml',
>     },
> });
> ```
> 
> ...
> 
> -   ❌ Do not `import` reporter as `import SonarReporter from 'vitest-sonar-reporter';`
> -   ✅ Define reporter as `reporters: ['vitest-sonar-reporter']` so that `vitest` will process it. This quarantees support for projects without `{ type: 'module' }`.
